### ISSUE TITLE
precmd disappears after CTRL+L

### ISSUE THREAD

**Issue by darenju** [sindresorhus/pure#114]
Hello,

Tried out Pure, and I'm quite happy with it. However, I find myself to clear the terminal often. CTRL+L clears the screen, but the part of the prompt where is displayed directory isn't shown. On first line of new screen, there's only the prompt char.

Happens on Terminal.app on OS X.
![capture d ecran 2015-05-22 a 21 57 52](https://cloud.githubusercontent.com/assets/1096215/7778646/9f4c86a6-00cd-11e5-8ac4-cb3bebf818a0.png)

**Comment by mafredri** [comment]
Unfortunately I do not know of an easy fix for your problem. This is how
zsh works and the precmd is only triggered after executing a command. Ctrl
+ l bypasses this. The only thing I can think of that could potentially
work is to bind ctrl+l to execute the clear command instead of relying on
the default behavior. I have not tried it and cannot anticipate if there
will be any side-effects or not.

**Comment by darenju** [comment]
Thanks for your help. I took inspiration in your suggestion, and bound CTRL+BACKSPACE to "send clear+return".
Hope this can help anyone else facing the same issue. Closing now.
