### ISSUE TITLE
Good prompt is too hard to differentiate from bad prompt

### ISSUE THREAD

**Issue by boushley** [sindresorhus/pure#134]
I really like the feature in this prompt where the prompt arrow "❯" changes colors based on the return code of the previous command, super helpful.

That said the current colors are too close. Would you be open to a change of colors? On my local copy I've changed `magenta` to `green` making it much easier for me to tell what happened.

**Comment by arthurvr** [comment]
> That said the current colors are too close

Are you using the [suggested theme](https://github.com/sindresorhus/pure#tips)? It's pretty clear IMHO.

**Comment by boushley** [comment]
I am not, but even in the screenshot the contrast isn't high. When you use `green` and `red` the contrast is much higher.

Maybe we could make this an option, something like `PURE_PROMPT_DEFAULT_COLOR`

**Comment by arthurvr** [comment]
I personally think it's high enough as-is and more beautiful than green and red.

**Comment by boushley** [comment]
Does that mean a pull request to allow configuring the color would be rejected?

**Comment by mafredri** [comment]
Personally I use `Tomorrow Night Bright`, here's how it looks:

![](https://www.dropbox.com/s/kl585014fm4hzkq/Screenshot%202015-06-25%2021.12.56.png?dl=1).

If you're dissatisfied with the contrast, I recommend tweaking your colors. Green would be very ugly in my opinion (this is after all a highly personal preference).

**Comment by boushley** [comment]
This is definitely a highly personal preference, that's why I'm hoping to make it configurable.

**Comment by mafredri** [comment]
Where would you draw the line? Option for default color, error color, maybe even git color, username color, etc.. I think in the spirit of this theme (simplicity) this should remain as is.

**Comment by arthurvr** [comment]
:+1: to what @mafredri said.

**Comment by boushley** [comment]
Welp glad I asked before opening a pull request.

**Comment by forivall** [comment]
Yeah, I would just maintain a fork and merge upstream changes as necessary.

**Comment by boushley** [comment]
@forivall that's the plan.

Although I don't know that I think that's simpler than having configuration options...

@mafredri I thought the spirit of this theme was visual simplicity with quite a bit of technical sophistication. The async Git checks, and the Git pull aren't "simple". They do make for a really clean and simple interface though when implemented in the more complex way that they are.

**Comment by mafredri** [comment]
@boushley I do get where you're coming from. I used to be of the opinion that everything should be configurable, but lately I try to lean more towards sensible pre-made choices. You're absolutely correct in that Pure is (at least not any more) simple in it's code base, however, I do have some reasons to prefer not to make colors configurable:

* More options removes from the simplicity of pure (just install 'n go)
* Allowing to change just one color seems unfair
* I feel that a theme, in it self, implies a pre-select layout and colors (which is the case here). All options (except the prompt symbol) are behavior related.

We do appreciate contributions and I hope you don't think otherwise, it's just that this one doesn't quite fit in. But perhaps @sindresorhus would also like to chip in?

**Comment by sindresorhus** [comment]
Yeah, I tend to favor being opinionated and going for the 90%. There's always going to be things people will want to configure. Where do we stop? After this, people will want to set their own prompt character, probably the other colors too, maybe the git dirty symbol, etc. I think "use what's here or download and modify if you want something different" has worked well so far. This is the first time changing the prompt color has come up since it was created back in 2012. I've looked at how Pure looks in a multitude of terminal themes and the difference between default and error state are totally legible in all of them. We can reconsider if more people complain about this, but for now I'll have to say it's not worth it, sorry.
