### ISSUE TITLE
prepromt on right side

### ISSUE THREAD

**Issue by onemanstartup** [sindresorhus/pure#159]
Could it be done? I want working directory to show up on right side, like RPROMT.
Couldn't find solution.

**Comment by mafredri** [comment]
I'm not quite sure what you're asking? Are you talking about a right-aligned preprompt or RPROMPT which sits on the right side of PROMPT?

Try typing this in your terminal: `RPROMPT='$prompt_pure_last_preprompt'`. Is that what you're looking for?

Either way, this is not possible with `pure` and is somewhat impractical, since if your prompt line grows too large, the directory and git info will disappear.

**Comment by onemanstartup** [comment]
Dunno, it's not like i forget right away when i'm typing, where I'm typing :)
But it's ok. I just want more minimalism) actually can live with what pure have now. it's great.

**Comment by mafredri** [comment]
Glad to hear :). I realize it's not like you just forget it, but the smaller the terminal / longer the path gets, eventually you won't see it at all, hehe.
