### ISSUE TITLE
Customizable dirty git symbol

### ISSUE THREAD

**Issue by justmytwospence** [sindresorhus/pure#167]
Would be nice

**Comment by sindresorhus** [comment]
Why? What would you use instead?

**Comment by justmytwospence** [comment]
Probably some nice unicode symbol.

**Comment by forivall** [comment]
this emoji: :imp: ?

**Comment by justmytwospence** [comment]
An exclamation mark, an X, any number of things as per people's tastes. If the prompt char is deemed worthy of customizing, I thought this char might also. No problem closing this if you disagree.

**Comment by mafredri** [comment]
The reason the unicode symbols are configurable is due to compatibility issues (see #139 for example). I can't say I have a solid stance on the issue, on the one hand I wouldn't want to introduce new options to pure, on the other hand, the dirty symbol is now the odd man out as the only one that is not configurable.

**Comment by mafredri** [comment]
Instead of leaving this issue open in perpetuity, I'm closing this with the following argument:

The `*`-character is not a valid branch name in git and can thus never have any other meaning in `pure` than indicating a dirty repo. Due to it's placement, the asterisk also increases visibility and is generally a pleasant character to look at. Finally, it's supported on all systems and fonts (I hope) so there really is no reason to provide a way to change it (as we had to with our other unicode characters).

With that, I'm sorry @justmytwospence, I hope you can grow to love the asterisk :)!

**Comment by forivall** [comment]
🙃

**Comment by bentomas** [comment]
I'm okay with the decision you've made, and am not trying to be difficult with this comment, and I will just have to maintain my own fork of this project so I can change the 1 character in the codebase, but I have to admit, I'm pretty baffled by this decision.  Respectfully, it seems to me the lines you're drawing are pretty arbitrary.  

Why is someone's technical compatibility issues any different than @justmytwospence's and my aesthetic compatibility issues?  Your stated goals are "pretty, minimal and fast", and with this decision you've made it clear that you are going to define what is "pretty" (asterisk is pleasant to look at) and "minimal" (no new options), so why are you even bothering to support systems that don't have those characters?  Why aren't you requiring those people to switch their font choice?

It seems to me you would either say, pure will look and work like this, without options, OR, pure will have limited options and those options will be intuitive and consistent (like you can choose any of the symbols). But instead you've said, lets have limited options in inconsistent ways, so some people can make aesthetic choices about how pure looks, but others can't.

I honestly don't know what the right answer is.  I can certainly see how adding more options can be a slippery slope.

**Comment by mafredri** [comment]
Thanks @bentomas for you input, and sorry for taking this long to reply. You bring an interesting perspective, and I'm painfully aware that allowing customization of only some prompt characters can be seen as inconsistent. It's something that bothers me as well.

In my view, pure's goal is to be beautiful (or beautiful enough) by default so that users don't feel the need to customize it, and those who do create their own theme. If something is bad, or could be better, it should be replaced by that something better. I also try to be open about changing any part of pure for the better, but to do that, I feel a good motivation for it is required.

So far I haven't seen any motivation for why a character, other than `*`, would be better suited for displaying the dirty status (obviously aesthetics, but that is both too subjective and subject to change over time). In the case of the other symbol options, people have been unable to use pure because of font or system limitations. That, in turn, has weighted more heavily over the *do not introduce new options*-mantra.

I guess one option to solve the *inconsistency* would be to remove the options for changing the prompt symbol and arrows, and replace it with a `PURE_SAFE_SYMBOLS` or something similar, which would change all characters to safer alternatives (with regards to fonts).

**PS.** Not relevant to the issue, but other options I'm looking to eliminate are `PURE_GIT_PULL`, `PURE_GIT_UNTRACKED_DIRTY` and `PURE_GIT_DELAY_DIRTY_CHECK`. Ideally these could be replaced with `PURE_GIT_IGNORE_DIRS=(/ignore/me /and/me)`. But I haven't put enough thought into that yet.
