### ISSUE TITLE
Couldn't read file containing theme pure

### ISSUE THREAD

**Issue by andrewdesigner** [sindresorhus/pure#174]
I get the following error when pure loads:

Couldn't read file /Users/Andrew/.oh-my-zsh/functions/prompt_pure_setup containing theme pure.

To clarify, pure seems to work fine, it just shows that error every time. Do you know what might be going wrong?

**Comment by mafredri** [comment]
Have you tested with a clean install of oh-my-zsh and following the instructions in the readme? I have no idea why you're seeing this and the error you're seeing makes absolutely no sense.

**Comment by zmwangx** [comment]
Now that I look at the oh-my-zsh instructions in README, I wonder why you need to 

> 1. Remove competing theme included in oh-my-zsh `~/.oh-my-zsh/themes/pure.zsh-theme`.

https://github.com/robbyrussell/oh-my-zsh/blob/22632aac7c99e02ec38223c84b2348435a82d1b5/oh-my-zsh.sh#L104-L112: The "competing theme" appears to be loaded only if `~/.oh-my-zsh/custom/pure.zsh-theme` or `~/.oh-my-zsh/custom/themes/pure.zsh-theme` is not present.

**Comment by mafredri** [comment]
The reason it's in the readme is that a user was having problems loading the theme, `~/.oh-my-zsh/themes/pure.zsh-theme` was being loaded instead of the pure. Removing the one in oh-my-zsh fixed the issue. Looking at the code, that really shouldn't happen, but ¯\_(ツ)_/¯. I'm all for reducing the possibility of error though, so I'm happy to keep it in the readme, there's really no downside.

**Comment by zmwangx** [comment]
It's one extra step and git wouldn't be happy. Other than that, not so much :)

Actually, why don't you submit a PR there as pure's maintainer, asking the horribly outdated version to be removed? (I guess removing it will affect some unsuspecting folks who do autoupdate, so a better approach might be adding a transitory message that's shown on startup, pointing to the official repo.)

**Comment by mafredri** [comment]
I don't think that's going to happen, the `pure` theme in oh-my-zsh is like pure was in the very beginning, but it's rewritten by Julien Nicoulaud (see [here](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/pure.zsh-theme)). Also, submitting pure to oh-my-zsh would also mean dealing with how zsh-async gets integrated and since I don't use it myself it's not really something I wish to deal with.

**Comment by mafredri** [comment]
@andrewdesigner is this problem still relevant to you?

**Comment by opticalgenesis** [comment]
sorry to drag this one up again, but I have followed all the instructions for oh-my-zsh installation, and I still seem to be getting this error? It would also appear that pure is not working at all when running zsh

**Comment by mafredri** [comment]
@opticalgenesis could you open up a new issue and provide additional details?
