### ISSUE TITLE
Pure uses SSH?

### ISSUE THREAD

**Issue by trusktr** [sindresorhus/pure#179]
Why might pure make my OS ask me for my SSH password?

**Comment by stibi** [comment]
Hi, you mean passphrase to a SSH public key?

**Comment by mafredri** [comment]
Pure does a `git fetch` when you are inside a git repository so that it can accurately display the up and down arrows indicating if you have unpublished or unpulled changes. If you do not wish to use this feature you can disable it, [see here](https://github.com/sindresorhus/pure#pure_git_pull). Alternatively you can configure your git repos in such a way that no SSH password is necessary.
