### ISSUE TITLE
adding editor_info to the prompt

### ISSUE THREAD

**Issue by aphecetche** [sindresorhus/pure#209]
Hi guys, 

Nice work with the pure prompt !

I'm using zprezto and I'd like to tweak the prompt a bit but I don't quite grok the logic of the modules/prompt/functions/prompt_pure_setup, so I was wondering if you could help. 

Basically I'd like to add the editor_info to know when I'm in normal mode etc... (I'm using vi mode). I'm just beginning with zsh so I'm sure that's the problem ;-) but what I've tried is to change the prompt_pure_setup function by adding : 

```
    zstyle ':prezto:module:editor:info:keymap:primary:insert' format 'I'
    zstyle ':prezto:module:editor:info:keymap:primary' format '>>>'
    zstyle ':prezto:module:editor:info:keymap:primary:overwrite' format 'O'
	zstyle ':prezto:module:editor:info:keymap:alternate' format '<<<'
    zstyle ':prezto:module:editor:info:completing' format '...' 
        
    # prompt turns red if the previous command didn't exit with 0
	PROMPT="%(?.%F{magenta}.%F{red})${PURE_PROMPT_SYMBOL:-❯}%f "
    RPROMPT="---${editor_info[keymap]}---"
```

At first it did nothing... Then I tried " autoload -U promptinit && promptinit\nprompt pure" (not sure which one(s) was needed) and now I have a right prompt display ------ whatever I do (i.e. it does not update dynamically). Plus I only get it when doing ssh, not in a regular shell.

Ok, as you see, I'm a bit at lost...

Regards,

**Comment by mafredri** [comment]
You seem to be using double quotes `"` in your `PROMPT` and `RPROMPT` definitions, this means that variable interpolation will be performed at definition time and will therefore never be updated. You must use single `'` quotes so that the `$` signs remain and no interpolation is performed at assignment time.

```console
❯ RPROMPT="---${editor_info[keymap]}---"
❯ typeset RPROMPT
RPROMPT=------

❯ RPROMPT='---${editor_info[keymap]}---'
❯ typeset RPROMPT
RPROMPT='---${editor_info[keymap]}---'
```

See the difference?

PS. There's actually a [cool trick](https://github.com/sindresorhus/pure/wiki#show-current-mode-when-using-vi-keybindings) in the wiki for displaying the current VI mode (the prezto method is quite simple).

**Comment by aphecetche** [comment]
Thanks. I indeed completely overlooked the single vs double quote issue...
