### ISSUE TITLE
Branch name is not expanded [regression]

### ISSUE THREAD

**Issue by CircleCode** [sindresorhus/pure#225]
since commit 6cbd49a, the prompt shows `$vcs_info_msg_0_` at the end (in a git repo, it is where the branch name should go, and in a folder without git, it is after the prompt)

**Comment by mafredri** [comment]
Yes, it seems this is a consequence of trying to fix #224 and user (un)setting of `prompt_subst`. Setting it with `setopt prompt_subst` would likely fix this in your case.

PS. I'm not implying you need to modify your setting of `prompt_subst` to fix the issue, just that it is likely the root cause.
