### ISSUE TITLE
Semi-colon should be used when autoloading promptinit

### ISSUE THREAD

**Issue by leoj3n** [sindresorhus/pure#226]
In regards to `promptinit`, why use `&&`? There is no return value to check; a semi-colon would suffice.

https://github.com/zsh-users/zsh/blob/master/Functions/Prompts/promptinit#L5

**Comment by mafredri** [comment]
I think it could be due to `autoload` coupled with `&&` is a common pattern you see around the net, although I have no idea where it originates from. I always assumed it was to prevent calling init if the autoloading had failed, but now I'm not so sure of it's purpose.

If you feel like making a PR, I'd gladly accept it.
