### ISSUE TITLE
Shows repo as not dirty when dirty on first prompt

### ISSUE THREAD

**Issue by CrazyPython** [sindresorhus/pure#235]
Upon shell startup:
```
~/blah master ⇡
❯ 

~/blah master* ⇡
❯ 
```
Dirty, but it shows as not dirty.

**Comment by mafredri** [comment]
I can't seem to reproduce the issue, even when opening a new shell in a git directory.

Could you give more details about your setup?

* Zsh version
* Terminal software and version
* If possible, a minimum reproduction case? E.g. the shortest `.zshrc` possible (without anything extra) that reproduces the issue?

**Comment by CrazyPython** [comment]
@mafredri 
1. zsh 5.0.8 (x86_64-apple-darwin15.0)
2. WebStorm Embedded Terminal
3. removing `$(thing --alias)` from .zshrc fixes it. Former structure is:
```
... # default stuff
autoload -Uz compinit && compinit
autoload -U promptinit; promptinit
eval $(thing --alias)
prompt pure
source /Users/james/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

Please note that the terminal is launched directly into the git repository.

**Comment by mafredri** [comment]
1. Upgrading to zsh 5.2 might help (and is recommended). The reason is, for versions prior to 5.2 zsh-async needs to use kill signals (`WINCH`) to signal process completion, whereas in 5.2 we can do it through monitoring the zpty fd with zle. At the very least you should be running zsh 5.1.1, because versions prior to this one has problems with kill signals that could result in a deadlock of the shell.
    * `brew install zsh`
    * `sudo vim /etc/shells`, add: `/usr/local/bin/zsh`
    * `chsh -s /usr/local/bin/zsh`
2. This is not a terminal we are supporting, but happy to help as long as it doesn't require custom hacks
3. What is `thing` and what's the output of `thing --alias` (without the `eval` and `$()`)?

I'm quite sure that the problem was not that `prompt pure` wasn't executed immediately after autoloading `promptinit`, I'm suspecting `thing` is doing something weird.

**Comment by CrazyPython** [comment]
@mafredri 

1. Good Idea.
2. It is a very lightweight wrapper, there is little to no customization outside of colors.
3. It's [thefuck](https://github.com/nvbn/thefuck) utility. (trust me, it's a productive terminal utility).  Full output:
```
alias fuck='TF_CMD=$(TF_ALIAS=fuck PYTHONIOENCODING=utf-8 TF_SHELL_ALIASES=$(alias) thefuck $(fc -ln -1 | tail -n 1)) && eval $TF_CMD && print -s $TF_CMD'
```

I don't know much shell scripting, but it seems pretty normal to me.

**Comment by mafredri** [comment]
@CrazyPython ok, that output looks benign, all I notice by adding `eval $(thefuck --alias)` to my zshrc is that it delays prompt initialization by A LOT, not sure if it's related.

> It is a very lightweight wrapper, there is little to no customization outside of colors.

Unless I'm mistaken, I don't believe it's just a lightweight wrapper, it's completely different terminal software. Just like Terminal and iTerm are completely different software. How else would it run inside the JetBrains IDE?

**Comment by CrazyPython** [comment]
@mafredri The terminal window is pretty ad-hoc, it doesn't have any extra features.

**Comment by mafredri** [comment]
@CrazyPython my point was just that the implementations are completely different. The minimalism of WebStorm terminal is of no relevance. For example, it's the terminal that implements ansi escape sequences, which is what we use to update/redraw the preprompt. Difference in implementation might result in different results.

Either way, I think we can consider this issue resolved, glad it's working just by moving the statement :)!
