### ISSUE TITLE
Is prezto still working?

### ISSUE THREAD

**Issue by step1step2** [sindresorhus/pure#238]
I guess I have to submit an issue on GitHub in the end. I was trying to get support in the #Node.js IRC channel on freenode.

Anyways. I had quite some trouble to understand weather or not `fpath=( "$HOME/.zfunctions" $fpath )` is optional or required. So many thing went wrong that and weird error occurred until now that I'm glad that I finally made it. I was originally trying to get prezto to work and I had to find a workaround to use an outdated version of ruby and gem in order to pass the rake install command.
It was really a hustle to get where I'm now. I did they same thing over and over again, now it finally works. I mean without errors.

> Set `zstyle ':prezto:module:prompt' theme 'pure'` in `~/.zpreztorc`.

I did that but nothing has changed. I mean my Terminal still looks the same:
![mycmder](http://i.imgur.com/L4ItLih.png)

[.zshrc](https://gist.github.com/anonymous/bc4682954f9b21153ad989a8936783c5)

**Comment by mafredri** [comment]
I don't understand the problem, and also, we don't provide support for using or installing zsh frameworks here.

1. Prezto does not require ruby or rake, why are you using a gem? Follow the 5-step installation guide from the [Prezto readme](https://github.com/sorin-ionescu/prezto#installation).
2. You have linked to a `.zshrc` for `oh-my-zsh`, I'm pretty sure you can't mix both prezto and oh-my-zsh.

My best recommendation: start from a clean slate (remove any zsh files in you home directory) and follow the installation instructions that I linked to.

I'm closing this since it doesn't seem pure related.

**Comment by step1step2** [comment]
> Pure is bundled with Prezto. No need to install it.

Why would I install Prezto then? I want my terminal to look like Prezto using pure-prompt. Is that possible?

**Comment by mafredri** [comment]
Pure and prezto are not related at all. If you use prezto, you have the OPTION of using pure without downloading anything extra (since it's bundled in prezto). This does not mean you should use prezto to use pure.
