### ISSUE TITLE
Cannot install on macOS - failed to execute ln

### ISSUE THREAD

**Issue by jleeothon** [sindresorhus/pure#282]
### General information

- Pure version: 1.5.0
- ZSH version: zsh 5.3.1 (x86_64-apple-darwin16.3.0)
- Terminal program & version: 1.1.0 (1.1.0.1408)
- Operating system: macOS Sierra 10.12.3 (16D32)
- ZSH framework: none

I have:
- [x] Tested with another terminal program and can reproduce the issue: Terminal (default macOS)
- [ ] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework -- don't have a framework installed

### Problem description

When installing through `npm`, the `postinstall` script fails because it it does not have permissions (probably sudo required). I did run the installation command (`npm install --global pure-prompt`) with sudo.

```
% sudo npm install --global pure-prompt
Password:

> pure-prompt@1.5.0 postinstall /usr/local/lib/node_modules/pure-prompt
> dest=/usr/local/share/zsh/site-functions; mkdir -p $dest && ln -sf "$PWD/pure.zsh" $dest/prompt_pure_setup && ln -sf "$PWD/async.zsh" $dest/async || echo 'Could not automagically symlink the prompt. Check out the readme on how to do it manually: https://github.com/sindresorhus/pure#manually'

ln: /usr/local/share/zsh/site-functions/prompt_pure_setup: Permission denied
Could not automagically symlink the prompt. Check out the readme on how to do it manually: https://github.com/sindresorhus/pure#manually
/usr/local/lib
└── pure-prompt@1.5.0 
```

During installation of `zsh` I got a problem with "insecure directories. Solved it by following this [piece of advice from SO](http://stackoverflow.com/a/13785716/3692286):

```
$ cd /usr/local/share/
$ sudo chmod -R 755 zsh
$ sudo chown -R root:staff zsh
```

I suppose the problem lies in having the right permissions in `/usr/local/share/zsh` and/or the `postinstall` script should try to use super user if there was a permissions failure (?).

### Reproduction steps

1. Install `zsh` with `brew install zsh`.
2. Solve problem with insecure directories with `cd /usr/local/share/ && sudo chmod -R 755 zsh && sudo chown -R root:staff zsh` as per suggestion of that SO answer.
3. Install `pure` with `sudo nom install --global pure-prompt`.

### My `.zshrc`:

```shell
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/othon/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
```

**Comment by mafredri** [comment]
Thanks for the details report @jleeothon. This is a know issue (related #176) but unfortunately there's not a whole lot we can do about it :/.

Typically users who have installed zsh through Homebrew do not experience this issue, in your case the default permissions have been changed which is why you ran into the issue. The *fix* you applied from SO it way more heavy-handed than necessary, it might have been better to track down whatever was causing the notice about insecure directories. Btw, correct me if I'm wrong, but don't these new permissions conflict with Homebrew, preventing it from ever updating/uninstalling zsh?

Now as a fix, I'm against using `sudo` in this instance, a `npm` module should never (IMO) ask for admin permissions, that's a red light. The only reasonable method I can think of is to create a fallback if linking fails, something like (pseudocode):

```zsh
link 2>/dev/null || \
    mkdir $PWD/functions && \
    ln -s $PWD/pure.zsh $PWD/functions/prompt_pure_setup && \
    ln -s $PWD/async.zsh $PWD/functions/async && \
    echo "Please add the following to your .zshrc:\n\n    fpath+=(\$fpath $PWD/functions)"
```

We could create the linking inside the modules own directory and ask the user to add an `fpath` to his configuration. Thoughts @sindresorhus?

**Comment by sindresorhus** [comment]
Can't we just block sudo usage? We've had great success with [`sudo-block`](https://github.com/sindresorhus/sudo-block) for CLI apps in Node.js. Could do something similar in ZSH.

**Comment by mafredri** [comment]
Ah sorry, I think my message wasn't clear enough. So the problem wasn't using `sudo npm install` in this instance, the problem is simply not having write permissions to `/usr/local/share/zsh/site-functions`.

The relevant part of my question basically starts from:

> The only reasonable method I can think of is to create a fallback if linking fails, something like (pseudocode):

As a proposal to avoid this in the future.

**Comment by sindresorhus** [comment]
Ah, I see. Your proposal sounds good.

**Comment by jleeothon** [comment]
Hey good people! Yes, the problem above was definitely caused by wrong permissions, although I probably finally solved it.

Seems to me like indeed there is not a single canonical consensus on what the right owner/permissions for `/usr/local` are, especially when you have more than one user account (specifically for `brew` users) on the computer, which is what I do. Playing with these permissions messes things up.

I got sleepy and mad at my computer yesterday midnight while solving this so let me apologise beforehand for the vagueness.

Two problems I noticed yesterday were:

First. While trying the "manual" instructions I ran into the problem where one of the symlinks that the project created was "hardcoded" into the expected location as of an `npm`. It is likely that it was caused by my trying to install multiple times from npm, then uninstalling, then retrying manually, etc. If someone else reports a similar problem, then maybe let's double check the source code for one such error.

Second. When opening new sessions, `zsh` complained that it could not execute `pure.zsh` and/or `async.zsh`. I see that in the original repo these files do indeed not have the `x` flag. I manually changed these permissions. Do you agree this is a problem, or was it likely caused by me messing up?

Unfortunately I lost my terminal output as of last night. Otherwise I would very gladly (beautify and) attach it here. Let me know if there's anything particular piece of information I can provide you with, or if I could try anything that helps you.

Cheers and thanks for the awesome repo!

**Comment by mafredri** [comment]
> First.

Not sure I follow? The `npm install -g prompt-pure` command does indeed create symlinks with absolute paths, but that is only if it is successful. Otherwise no symlinks are created.

> Second.

Neither `pure.zsh` nor `async.zsh` require the executable flag since they should not be invoked as commands. Preferably they should be `autoload`ed, by residing in the `$fpath` or sourced via `source ./path/to/async.zsh; source ./path/to/pure.zsh`.

> Cheers and thanks for the awesome repo!

Your welcome, hope you enjoy pure!

PS. I would appreciate it if you take a look at #285 and let me know if you think it's an acceptable resolution to this issue.

**Comment by jleeothon** [comment]
#285 Looks good to me. Thanks!

> First.

Elaborating on it, I tried something like:

1. Tried to install with `npm install -g prompt-pure`. Failed due to permissions.
2. Tried to install with manual instructions. Failed because (something?) was trying to use nom-specific directories although these were the "manual" instructions.

> Second

I tried reproducing the problem I ran into by e.g. running

```
sudo chmod -x /usr/local/share/zsh/site-functions/prompt_pure_setup
sudo chmod -x /usr/local/share/zsh/site-functions/async
sudo chmod -x /usr/local/lib/node_modules/pure-prompt/pure.zsh
sudo chmod -x /usr/local/lib/node_modules/pure-prompt/async.zsh
```

Although the very least for the files under `/usr/local/share/zsh/site-functions/`, seems I didn't get chmod right (what did I miss?) because the file does still have the `x` bits set after.

Let me know if there's anything I can try for you. Otherwise feel free to dismiss this ticket.

**Comment by mafredri** [comment]
Thanks for looking at the PR!

Generally, with #285, I think we can consider this ticket resolved since there's nothing we can do about weird permission issues. We try to make it work in the common case and be helpful if it fails.

> I tried reproducing the problem I ran into by e.g. running

You can't modify the flags of a symlink. By running `chmod` against a symlink you are actually modifying the file it points to, this is why the files in `/usr/local/share/zsh/site-functions/` look unaltered.
