### ISSUE TITLE
Trying to issue new line before prompt character

### ISSUE THREAD

**Issue by mikeerickson** [sindresorhus/pure#310]
### Problem description

I have the following `modified` prompt and all is perfect except I want a \n before the caret ( > )

### Reproduction steps

Using the following prompt

```
PS1="$fg[cyan]%n@%m%f • %{$fg[cyan]%}%~%{$reset_color%} $(git_prompt_info)%(?.%F{green}.%F{red})❯ %F{white}"
```

I have tried to place a `\n` before prompt, but that displays the literal `\n`

```
vagrant@homestead • ~/code/l55-test \n❯
```

I am wondering if there is some `%?` tag to use instead of the `\n` tag?

**Comment by mikeerickson** [comment]
Hey gang, anybody have advise on this one :-)

**Comment by mafredri** [comment]
I don't see how this is related to Pure, but I'll play along 😃.

It doesn't quite work to specify a newline via `\n` in the prompt string.

You could instead define a newline variable which you then use in the prompt:

```zsh
prompt_newline=$'\n%{\r%}'

PS1="$fg[cyan]%n@%m%f • %{$fg[cyan]%}%~%{$reset_color%} $(git_prompt_info)%${prompt_newline}(?.%F{green}.%F{red})❯ %F{white}"
```

Here we use `$''` to set a literal newline (instead of an escape sequence) in the variable `prompt_newline`. We also tell the prompt via `%{}` that `\r` doesn't take up any space (character width) in the prompt.

With this set, you should be able to call `zle && zle .reset-prompt` to update the prompt at any time.

**Comment by mikeerickson** [comment]
@mafredri I guess it is not related to pure (more reveals my lack of knowledge of how it works under the hood). Thx for information, makes plenty of sense ;)
