### ISSUE TITLE
PROMPT is not updated

### ISSUE THREAD

**Issue by hongzhouye** [sindresorhus/pure#333]
### General information

- Pure version: 1.x.x (Sorry I did not find it. I downloaded it on Jul. 29.)
- ZSH version: 5.0.8
- Terminal program & version: OS X Terminal 2.6.1
- Operating system: macOS El Capitan 10.11.6
- ZSH framework: oh-my-zsh (maybe? how can I check?)

I have:
- [ ] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
I want to move git branch name to `PROMPT` instead of `preprompt`. I tried this by adding
```shell
if [[ -n $prompt_pure_vcs_info ]]
then
    PROMPT+="%F{white}"'${prompt_pure_vcs_info[branch]}${prompt_pure_git_dirty}%f'
fi
```
at the end of function `prompt_pure_setup()`. However, I found that this `if` statement is evaluated only once (i.e. when you open a new terminal).

### Reproduction steps

see `Problem description`

### My `.zshrc`:

nothing is needed in `.zshrc`

```shell
autoload -U promptinit; promptinit
prompt pure
```

**Comment by mafredri** [comment]
First off, I see you are using zsh `5.0.8`, if possible, updating is highly recommended. Newest would be best, otherwise `>=5.2` would be preferable, or at least `5.1.1`.

Since you want to move the git branch from preprompt to prompt, I highly recommend making the changes straight to the pure source, no need to guard it behind an `if` statement. You will have to modify the source to remove it from preprompt anyway.

But moving the git branch is not a feature or a part of Pure, so I'm closing this as a non-issue. Feel free to ask if you have more questions though.
