### ISSUE TITLE
Sometimes Pure clears the output of the previous line

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pure#356]
### General information

- Pure version: 1.5.2
- ZSH version: 5.4.2
- Terminal program & version: iTerm 3
- Operating system: macOS 10.13
- ZSH framework: None

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

```
~/dev/oss/npm-home master*

~/dev/oss/npm-home master ⇡
❯ o

~/dev/oss/npm-home master ⇡
❯ o
```

Notice how `o` is missing from the first prompt line. I wrote and executed it there, but it got cleared right after. I also see this problem pretty often with the last line being cleared of the output of [`np`](https://github.com/sindresorhus/np), [relevant issue](https://github.com/sindresorhus/np/issues/158).

It seems like it's being cleared when `⇡` is added.

This issue only happens once in a while and not consistently, which makes me believe it's something with the async setup and maybe a race issue.

**Comment by 4cm4k1** [comment]
* Pure version: 1.5.2
* ZSH version: 5.4.2 (x86_64-apple-darwin17.0.0)
* Terminal program & version: Hyper 2.0.4 (canary)
* Operating system: macOS 10.13.1 Beta 2 (17B35a)
* ZSH framework: Zplug 2.4.1

I also experience this issue once in a while, typically after exiting `git log`, `nano`, or making a commit.

**Comment by mafredri** [comment]
Does this also happen on the master branch or is it limited to 1.5.2? Thinking it might be time we cut a new release.

**Comment by sindresorhus** [comment]
Master

**Comment by mafredri** [comment]
Hmm, since master is using `zle reset-prompt`, I'd imagine this must either be a bug in zsh (specifically ZLE) or then our use case puts more pressure on it than it was designed for.

It could be that:
* ZLE is in a weird state when we're calling `zle reset-prompt`
* A previous `zle reset-prompt` is active when we call `zle reset-prompt` again (due to async tasks finishing quickly)

Out of interest, is there a chance that you had any form of zsh completion (or similar) active when the bug was triggered?

I'll try to dig into this and see what I can find.

**Comment by sindresorhus** [comment]
> Out of interest, is there a chance that you had any form of zsh completion (or similar) active when the bug was triggered?

Yes, sometimes, but it's also triggered without, like with https://github.com/sindresorhus/np/issues/158.

**Comment by mafredri** [comment]
Ok, so I think I finally hunted down the cause for this, and pushed a potential fix for it in the `async-render-fix` branch (https://github.com/sindresorhus/pure/commit/03a81d07d14ecd55a2ebffbb220fe7b501b26ed6).

It's an interesting issue, and it might be a bug in ZSH, but ultimately this should result in us doing fewer prompt updates, which is a win. I hot-patched zsh-async as well since I needed some additional information from it.

The behavior is now that if there is any async_job result pending, we will not redraw the prompt until the last async_job result is in (see commit for more details). I still need to vet that there is no situation where an async job wants to refresh the prompt, but the next one doesn't care to (and ultimately prompt is not redrawn). A global variable should probably take care of this though.

Apologies for the wild ride.

**Comment by mafredri** [comment]
Oh and I managed to reproduce it reliably. I didn't know what `o` was, so I invented my own:

```
integer num=0
_o() {
    if [[ -f $num ]]; then
        git add $num && git commit -m $num &>/dev/null; ((num++))
    else
        touch $num
    fi
}
alias o=_o
```

Typing `o` (two times) would now trigger the issue in a git repository with an upstream.

**Comment by sindresorhus** [comment]
> Ok, so I think I finally hunted down the cause for this, and pushed a potential fix for it in the async-render-fix branch (03a81d0).

Yay! I'll try to run it for a few days.

> I didn't know what o was, so I invented my own:

```sh
❯ which o
o () {
	if [ $# -eq 0 ]
	then
		open .
	else
		open "$@"
	fi
}
```

**Comment by Alok** [comment]
I run into a similar-sounding issue, where this prompt causes some widgets to not be drawn correctly.

**Comment by mafredri** [comment]
@Alok does the `async-render-fix` branch help with your issue? If not, please open a new issue since it's unlikely the same and I have nothing to go on based on your comment 😄.

**Comment by sindresorhus** [comment]
> Ok, so I think I finally hunted down the cause for this, and pushed a potential fix for it in the async-render-fix branch (03a81d0).
> > Yay! I'll try to run it for a few days.

I have yet to see the issue now ✨

**Comment by mafredri** [comment]
Great, thanks for testing! It's been working well on my end as well, so I pushed a new `zsh-async` release and opened my branch up as a PR, but basically nothing (except git history) has changed in between 😄.

**Comment by mafredri** [comment]
@mohitmun no, this issue was not related to zsh-users 15729. Read https://github.com/sindresorhus/pure/commit/a3b22b242d2e4bc8d7e989c47e49a4bf03d7e2ab for more info.
