### ISSUE TITLE
Getting prompt to redraw on widget execution

### ISSUE THREAD

**Issue by Alok** [sindresorhus/pure#360]
### General information

- Pure version: 1.5.2
- ZSH version: 5.4.2
- Terminal program & version: Kitty
- Operating system: macOS 10.11.6
- ZSH framework: none

I have this widget which goes up one directory when I press `alt-p`. The issue is that it does not update part of the prompt. If the parent isn't a git repo, the `master* ⇡` doesn't go away. I have to hit enter to completely redraw the prompt, which isn't what I want since this is meant to be a really fast way of going up a directory.

```
cd-parent-widget() {
  cd ..
  zle reset-prompt
}
```

**Comment by mafredri** [comment]
Pure performs it's refresh logic in the `precmd`-hook which is why the prompt isn't updated. You can force Pure to do this by replacing `zle reset-prompt` with:

```zsh
prompt_pure_async_tasks
prompt_pure_preprompt_render
```

The call to `prompt_pure_preprompt_render` is optional though, since it will be triggered by the async tasks anyway.

I realize it might make sense to trigger it in a `chpwd`-hook as well, I will think about this.
