### ISSUE TITLE
git stash

### ISSUE THREAD

**Issue by jpresley23** [sindresorhus/pure#365]
I read the discussion in Issue #317 and understand the concern to not have a messy prompt. The right prompt suggestion is a decent workaround but the problem is that shows a message when there are no changes in stash. For a light user of stash, the constant 0 in the right hand side of the screen is a distraction. Changing that requires building a function that indicates it may be more appropriate.

I use stash to store work in progress changes that I don't want to commit before I re-integrate master into my branch. It's useful to see an indicator if there are changes in stash I forgot about if I get interrupted in my workflow. I used a custom prompt that someone at work shared around that used something like `*` to indicate there is something in your stash.

Would it be a good compromise to add the stash indicator functionality but set a default minimum threshold before there is an indicator that could be changed with an environment variable? For example, the default could be a high number, say. Those who are light stash users could override that and set it to 0.

The alternative is to create a super light "pure-stash" indicator that is separate from pure.

**Comment by jpresley23** [comment]
@leoj3n I'm curious on your thoughts since you opened the original issue.

**Comment by henrywallace** [comment]
Alternatively, is it possible to allow calling some custom function for displaying git information? Where I still want to use the rest of pure prompt, but insert my own git information.

**Comment by KlausHartl4242** [comment]
I'd love to see support for stashes... at the moment I've hacked something into `prompt_pure_preprompt_render()` on my own machine, the result looking like:

<img width="451" alt="screenshot 2019-02-08 at 19 05 37" src="https://user-images.githubusercontent.com/40851765/52496940-12814180-2bd5-11e9-856d-f5d1381ca04e.png">

If there are any stashes, the yellow ≡ icon is shown, otherwise not... (similar to how in and outgoing arrows behave) 

(I would be happy to prepare a PR for this.)

PS: Icon and color is inspired by https://github.com/michaeldfallen/git-radar, which I recently migrated from to pure...

**Comment by carhartl** [comment]
I'd love to see support for stashes... at the moment I've hacked something into `prompt_pure_preprompt_render()` on my own machine, the result looking like:

<img width="451" alt="screenshot 2019-02-08 at 19 05 37" src="https://user-images.githubusercontent.com/21918/52497299-fd58e280-2bd5-11e9-8404-ff6e97dfcbb1.png">

If there are any stashes, the yellow ≡ icon is shown, otherwise not... (similar to how in and outgoing arrows behave)

(I would be happy to prepare a PR for this.)

PS: Icon and color is inspired by https://github.com/michaeldfallen/git-radar, which I recently migrated from to pure...

**Comment by carhartl** [comment]
Might be even nicer to have the icon the same color as the arrows, though I'm not a designer :)

**Comment by carhartl** [comment]
Here's the implementation: https://github.com/sindresorhus/pure/compare/master...carhartl:git-stash-support

It would need some polishing I guess, making the icon configurable (similar to the arrows) and so on.

**Comment by joeytwiddle** [comment]
For what it's worth, in my version of [git-aware-prompt](https://github.com/joeytwiddle/git-aware-prompt) I only show the stash indicator if the stash was made **on the current branch** (or on top of the current commit).

That suits my workflow, because it doesn't distract me when I am working on a different branch, but when I switch back to the original branch, the indicator reminds me I need to pop. You may consider the feature that way. [Code is here](https://github.com/joeytwiddle/git-aware-prompt/commit/21fe00ae0425417e1de510fafe6ae963d86078e2) but not beautiful!

**Comment by fauust** [comment]
> I read the discussion in Issue #317 and understand the concern to not have a messy prompt. The right prompt suggestion is a decent workaround but the problem is that shows a message when there are no changes in stash. For a light user of stash, the constant 0 in the right hand side of the screen is a distraction. Changing that requires building a function that indicates it may be more appropriate.

See https://github.com/sindresorhus/pure/issues/317#issuecomment-529947677 for a Q&D hack.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/pure/pull/462.
