### ISSUE TITLE
False SSH connection detected

### ISSUE THREAD

**Issue by sudo-nice** [sindresorhus/pure#403]
### General information

- Pure version: up to date master
- ZSH version: 5.5.1
- Terminal program & version: rxvt-unicode v9.22
- Operating system: Debian Stretch
- ZSH framework: none

### Problem description

This [commit](https://github.com/sindresorhus/pure/commit/17e23aecda563f6135b91d0d2eea82dadb0ca070) causes the appearance of `user@host` in my prompt even when I'm not connected via ssh. Some investigation:

```
echo "@${SSH_CONNECTION}@" -> @@
echo $+commands[who]       -> 1
who am i                   -> user pts/6 2018-05-04 19:10 (:0)
```

**Comment by mafredri** [comment]
Your issue should be fixed by #398 but unfortunately that fix is also insufficient, which is why it hasn’t been merged yet. Sorry for the trouble!

**Comment by sudo-nice** [comment]
Not a big deal. I'm closing this issue, since the problem is known and being working on.
Thank you for a great prompt!

**Comment by mafredri** [comment]
@sudo-nice I believe #398 should now fix your issue as well, would you mind giving it a spin.

**Comment by sudo-nice** [comment]
Confirm, it's fixed, thank you!

**Comment by 0xC0FFEE** [comment]
Unfortunately the fix does not work for me. Maybe this relates to `who -m` returning an empty string on my machine?

**Comment by mafredri** [comment]
@0xC0FFEE could you open a new issue describing your problem? I don't see how `who -m` returning an empty string could result in false ssh connection detection.

**Comment by 0xC0FFEE** [comment]
@mafredri Thanks for your quick reply. I've debugged the issue further and found out, that `PROMPT_PURE_SSH_CONNECTION` is set to `HH:MM` of my previous boot (e.g. `14:20`). 

If I set `PROMPT_PURE_SSH_CONNECTION` to an empty value in my `.zshrc` the problem is fixed. Should I still open an issue for this?

**Comment by elwarren** [comment]
This appears to also break on macOS when coreutils is installed with brew and `/usr/local/opt/coreutils/libexec/gnubin/who` placed in `$PATH` ahead of the native `/usr/bin/who` command.

```
❯ /usr/local/opt/coreutils/bin/gwho
user console      2018-06-04 18:32
user ttys002      2018-06-04 21:22
user ttys003      2018-06-04 20:49

~
❯ /usr/local/opt/coreutils/bin/gwho -m
user ttys002      2018-06-04 21:22

~
❯ /usr/local/opt/coreutils/bin/gwho am i
user ttys002      2018-06-04 21:22

~
❯ /usr/bin/who
user console  Jun  4 18:32
user ttys002  Jun  4 21:22
user ttys003  Jun  4 20:49

~
❯ /usr/bin/who -m
user ttys002  Jun  4 21:22
```

The `/usr/local/opt/coreutils/libexec/gnubin/who` is a symlink to `/usr/local/opt/coreutils/bin/gwho` and my resolution was to simply remove the link `rm /usr/local/opt/coreutils/libexec/gnubin/who`

**Comment by jenniges** [comment]
I maybe had the same issue as @0xC0FFEE.
I don't use a DE and `who -m` inside the linux terminal outputs:
```
user     tty1         2018-06-06 11:10
```
from there on _pure_ exports `PROMPT_PURE_SSH_CONNECTION=11:10` because the login time is a valid IPv6, like @mafredri already figured out. `startx` passes the export down to the window manager and all terminals have `PROMPT_PURE_SSH_CONNECTION` falsly set.

I fixed it by altering `reIPv6` to `([a-f0-9]*:){2,}[a-f0-9:]*`. This way an ipv6 address has to contain at least two colons. There may be better solutions, but I think this one isn't much more wrong and complex than before.
Catches: `::1`, `1::` but also incorecctly `1::::::2`, and **not** `1:2`, which is also not a valid ipv6-address.

**Comment by mafredri** [comment]
Sorry for the long wait. I've now pushed #413, I would appreciate if @0xC0FFEE, @elwarren and @jenniges could test!

And thanks @jenniges for the suggestion, I went with something similar (although a bit stricter).

@elwarren gwho should work as expected now (in #413) 😄.
