### ISSUE TITLE
Weird tab autocomplete glitch on alacritty

### ISSUE THREAD

**Issue by rawaludin** [sindresorhus/pure#412]
### General information

- Pure version: master
- ZSH version: 5.3
- Terminal program & version: Alacritty
- Operating system: macOS Sierra 10.13.5
- ZSH framework: zim

I have:
- [ ] Tested with another terminal program and can reproduce the issue:
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
I'm not really sure where to post it. I got weird duplicate of current command on alacritty. This not happen if:

1. Use pure in other terminal.
2. Use other theme in alacritty.

### Reproduction steps

1. Install alacritty
2. Install zim
3. type `cd` then tab. The `cd` become `cdcd`

<img width="315" alt="with-prompt-plugin" src="https://user-images.githubusercontent.com/1274849/41263000-4d896c92-6e0e-11e8-809e-36073cb0bbff.png">

If this was problem in alacritty, other themes should behave the same. But this bug only shown if I use pure.

I really like your themes and have been using it for a long time. Hopefully there's a solution to this.

Thanks for taking your time to build this theme & review my ticket 🙇

**Comment by mafredri** [comment]
I can't reproduce this in Alacritty using my own setup, or even when using *pure* Pure (without other configs).

There have been many previous similar issues, sometimes due to Hyper, other times due to framework (e.g. oh-my-zsh or prezto) or bugs, but I can't think of what in Pure could cause this right now.

This could be an issue with zsh being unable to calculate the width of the text, for whatever reason. You can try [this suggestion](https://github.com/sindresorhus/pure/issues/300#issuecomment-328744993) by elvis-macak.

```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

If that doesn't help, my guess it's something that's hooking into ZLE, maybe performing some action during completion. I'm not at all familiar with zim though.

**Comment by rawaludin** [comment]
This is working.
Thank you very much!

**Comment by gabyx** [comment]
For docker do the following before install on Debian:

 ```shell
# Set the locale
RUN apt-get install -y locales && \
    dpkg-reconfigure locales && \
    locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

```
