### ISSUE TITLE
pyenv support

### ISSUE THREAD

**Issue by flrgsr** [sindresorhus/pure#423]
### General information

- Pure version: 1.7.0-1
- ZSH version: 5.5.1
- Terminal program & version: Konsole (KDE)
- Operating system: Manjaro Linux x86_64
- ZSH framework: oh-my-zsh

### Problem description

I have searched on this topic and it seems it have been coming up multiple times in the past that people asked (and solved?) this problem.

Yet I was unable to get to a working solution that displays my current pyenv environment.
Could someone kindly guide me to the definite solution or tell me what exactly I need to modify to make this work.

Thanks

**Comment by mafredri** [comment]
If you're using pyenv virtualenv, you can do `pyenv activate my_virtualenv` and it will work. If you're not, you can try something like:

```zsh
precmd() {
    if [[ -n $PYENV_SHELL ]]; then
        local version
        version=${(@)$(pyenv version)[1]}
        if [[ $version = system ]]; then
            unset VIRTUAL_ENV
        else
            VIRTUAL_ENV=$version
        fi
    fi
}
```

This is untested. It was previously mentioned in https://github.com/sindresorhus/pure/issues/221#issuecomment-236372279 using a slightly different approach (but we no longer need to change PROMPT).

**Comment by flrgsr** [comment]
> If you're using pyenv virtualenv, you can do pyenv activate my_virtualenv and it will work.

it does not work. 

What would I do with the above function? Add it to `pure.zsh`? Where does it get called?

**Comment by mafredri** [comment]
> it does not work.

It should, but perhaps you have disabled it? Could you give the output of:

```zsh
typeset -p VIRTUAL_ENV_DISABLE_PROMPT
```

> What would I do with the above function? Add it to pure.zsh? Where does it get called?

It's completely unrelated to Pure, you can set in in your `.zshrc` wherever. `precmd` is a zsh hook that gets called before a prompt is displayed.

**Comment by flrgsr** [comment]
the output of 

`typeset -p VIRTUAL_ENV_DISABLE_PROMPT`

is

`export VIRTUAL_ENV_DISABLE_PROMPT=1`

**Comment by mafredri** [comment]
That’s the reason it doesn’t work, Pure is respecting your choice 😄. If you remove wherever you’ve defined that, it should start working.

You can test with `unset VIRTUAL_ENV_DISABLE_PROMPT`, although that will only work temporarily.

**Comment by flrgsr** [comment]
Mhh strange, I did not change anything beyond the vanilla installation. 

After I do ```unset VIRTUAL_ENV_DISABLE_PROMPT``` the value is ```export VIRTUAL_ENV_DISABLE_PROMPT=12```

**Comment by mafredri** [comment]
You need to search your environment / profile (e.g. `.zshrc`) and remove the line that says `VIRTUAL_ENV_DISABLE_PROMPT=1`.

If you don't know where you have it defined, you can try to run `zsh -x` (debug output) and inspect the output, if you're lucky you will find it there.

And if you can't find it, well, you can always throw `unset ...` at the end of your `.zshrc`. I wouldn't recommend this, though, since keeping a clean shell configuration leads to happiness (in this case, it would be "unclean" because there are two conflicting statements, one that sets to 1, another that removes).

**Comment by fazlearefin** [comment]
I had the same issue. Trying `unset VIRTUAL_ENV_DISABLE_PROMPT` worked temporarily.

After some through search, I found out I was using the `virtualenv` plugin from `oh-my-zsh` in my `~/.zshrc`. Removing  `oh-my-zsh virtualenv` plugin from my `~/.zshrc` solved this issue.

**Comment by mafredri** [comment]
Thanks for your input @fazlearefin. Good to know that the `virtualenv` plugin might cause issues. I just pushed a commit that advices against enabling incompatible plugins (https://github.com/sindresorhus/pure/commit/fbc7d825c1412b8787f4f07f2f1fa7526afdb8c4).

And with that, I believe this issue is solved.
