### ISSUE TITLE
[FEATURE REQUEST] Show exit codes of previous command in prompt

### ISSUE THREAD

**Issue by NightMachinary** [sindresorhus/pure#447]
https://github.com/bhilburn/powerlevel9k shows the exit codes of the previous command very gracefully, something like `0|1` for piped commands. I really miss this feature.

**Comment by mafredri** [comment]
Would something like this work for you @NightMachinary?

```zsh
RPROMPT='${(j.|.)pipestatus}'
```

Since Pure doesn't touch the RPROMPT, it's free to display anything you wish 😄. Not sure that this feature would be a good fit with Pure as we already indicate exit status via color and generally Pure tries to be clutter-free. Showing the specific exit code and/or multiple exit codes would make it more cluttered IMO.

**Comment by NightMachinary** [comment]
Thanks, I think it should work. 👍🏼💚

**Comment by sindresorhus** [comment]
I don't want this for Pure, but would be nice to have it as a tip in the wiki: https://github.com/sindresorhus/pure/wiki

**Comment by mafredri** [comment]
Done! https://github.com/sindresorhus/pure/wiki/Home/_edit#show-exit-code-of-all-piped-commands-in-rprompt

@NightMachinary the tip in the wiki is a slightly improved version which will remember the status when you hit [Enter] 😄.
