### ISSUE TITLE
control pre line feed with env variable

### ISSUE THREAD

**Issue by deadc0de6** [sindresorhus/pure#469]
Thanks for this awesome prompt!
Would it be possible to have an environment variables like `PURE_PRE_LINE_FEED` to control if a line feed is inserted before displaying the prompt?

**Comment by mafredri** [comment]
Why do you want to disable it?

There are two reasons for it being there:
1. We think it looks good
2. It solves (two) issues related to prompt usability

Regarding 2, the issue is that either your prompt is not guaranteed to start on a new line (think `print -n`) or you must enable `setopt PROMPT_CR PROMPT_SP`. While `PROMPT_CR` and `PROMPT_SP` solve the issue, it fills the prompt line with space characters, so if you ever copy paste the output, it will be filled with spaces.

Here's an image without newline, and without `CR/SP` (see how path `~` starts on the wrong line):
<img width="198" alt="image" src="https://user-images.githubusercontent.com/147409/56289732-4ecba380-612a-11e9-8c88-d0903f2cdf47.png">

And here's one without newline, but `CR/SP` enabled:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/147409/56289869-a2d68800-612a-11e9-9f29-d83b98710691.png">

The highlighted part is filled with spaces.

**Comment by deadc0de6** [comment]
I see, fair enough, haven't thought of these use-cases. I'll keep the line feed then.
Thanks for the information!
