### ISSUE TITLE
Terminal Marks don't work

### ISSUE THREAD

**Issue by RexYuan** [sindresorhus/pure#476]
### General information

- Pure version: 1.9.0
- ZSH version: 5.3 (x86_64-apple-darwin18.0)
- Terminal program & version: Terminal Version 2.9.5 (421.2)
- Operating system: macOS Mojave 10.14.5
- ZSH framework: antigen (I get the same problem when not loading antigen too)

I have:
- [] Tested with another terminal program and can reproduce the issue: I did not check other programs
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
I can't use the go to "previous/next mark" navigation in Termina properly anymore. They should go to the previous/last command prompt. If I load the pure theme now they just go to the first/last line. If I don't load the theme it works properly. I've also tried reinstalling the theme but it didn't work.

### Reproduction steps

1. Load the theme
2. Use the options in Edit > Marks

### My `.zshrc`:

Just loading the theme causes the problem on my machine

```shell
autoload -U promptinit; promptinit
prompt pure
```

If I take out the second line it works again.

**Comment by mafredri** [comment]
Thanks for reporting. This seemed like a regression and indeed, it appeared when we added VI-mode support.

The problem lies in calling `zle prompt-reset` in the `zle-line-finish`-hook. The way Terminal inserts the prompt marks are incompatible with performing a prompt reset at this point, which is unfortunate.

We could work around this issue by simply not performing the reset, which alters the behavior a bit. Now, when the user is in VI-mode with prompt symbol `❮`, and hits enter, the symbol will reset to `❯` before continuing / showing the next prompt. With the change, however, the symbol would remain `❮`, which isn't wrong per-se.
