### ISSUE TITLE
Remove empty line

### ISSUE THREAD

**Issue by qazip** [sindresorhus/pure#509]
There is an empty line between subsequent prompts. This can be seen in the image that it is in the README. For example, there is a line between "Exit 1" and "~".

Is it possible to remove this line? I find it wastes to much space.

**Comment by PerBothner** [comment]
Note that with [shell integration](http://localhost/per/blog/2019/shell-integration-proposal/) a terminal can use some other visual separator between commands, so the empty line is redundant.

**Comment by 0xBADDCAFE** [comment]
I locally patch like this:

```diff
diff --git a/pure.zsh b/pure.zsh
index ddb0e30..3dad87d 100644
--- a/pure.zsh
+++ b/pure.zsh
@@ -176,7 +176,7 @@ prompt_pure_preprompt_render() {
 
 	if [[ $1 == precmd ]]; then
 		# Initial newline, for spaciousness.
-		print
+		# print
 	elif [[ $prompt_pure_last_prompt != $expanded_prompt ]]; then
 		# Redraw the prompt.
 		prompt_pure_reset_prompt
```

It is prefer to keep current behavior for other users, so how about create new option value like `PURE_STRIP_NEW_LINE` ?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/pure/pull/526#issuecomment-583774870

**Comment by bishopb** [comment]
You can hack around pure's _current_ opinion with a custom implementation of `print`:

```sh
print() { [ 0 -eq $# -a "prompt_pure_precmd" = "${funcstack[-1]}" ] || builtin print "$@"; }
```

This implementation of `print` masks the built-in. When `print` is called with zero arguments inside a function named `prompt_pure_precmd` it does nothing (instead of printing an empty line); otherwise it behaves exactly as the print built-in.

Put this in your .zshrc before initializing pure and you're good to go.

Future updates to how pure behaves may invalidate this hack. Caveat emptor.

**Comment by james-prado** [comment]
@bishopb Is there anyway to prevent the new line **only** when the terminal is `clear`ed or when first opening the terminal?

When I open a new terminal this happens:
![before_clear](https://user-images.githubusercontent.com/13836920/90339076-718af800-dfbc-11ea-8b3d-7603ea9249ec.png)

The custom `print()` function works well, but I only want to run it when the terminal is first opened, or after running `clear`. Do you know how to do something like this?

**Comment by bishopb** [comment]
> The custom `print()` function works well, but I only want to run it when the terminal is first opened, or after running `clear`. Do you know how to do something like this?

@james-prado, not easily: you'd have to provide context to that `print` function so that it was aware when it was called in those conditions. I'd probably approach it by using an environment variable to keep track of the state, making an alias for `clear`, checking for a login shell's command depth, etc. Pretty gnarly.

**Comment by james-prado** [comment]
@bishopb Thanks for the reply. Yea that's a fair bit to go through just to remove a new line. I've learned to live with it for now.

**Comment by LangLangBart** [comment]
> Do you know how to do something like this?

Using @bishopb's function and a slightly modified function from [stackoverflow](https://stackoverflow.com/questions/20512957/zsh-new-line-prompt-after-each-command/50103965#50103965)  this works for new tabs/windows, but not for `clear`.
![Screenshot 2022-02-17 at 17 29 04](https://user-images.githubusercontent.com/92653266/154528891-f187b4be-577e-4612-a844-321139a3e1ff.jpg)
