### ISSUE TITLE
Pre-prompt line written twice, causing problems for shell integration

### ISSUE THREAD

**Issue by PerBothner** [sindresorhus/pure#520]
The pre-prompt is written twice, which is both inefficient and causes some problems with "shell-integration".

*Background*: I'm working on an extended [protocol](https://gitlab.freedesktop.org/Per_Bothner/specifications/blob/master/proposals/semantic-prompts.md) for enhanced "shell integration" - see [article with screenshots](http://per.bothner.com/blog/2019/shell-integration-proposal/). I wrote [a zsh script](https://github.com/PerBothner/DomTerm/blob/master/tools/shell-integration.zsh) to implement the protocol: It essentially adds an invisible prefix and postfix to `PROMPT`, specifically:

    PS1=$'%{\e]133;P;k=i\a%}'$PS1$'%{\e]133;B\a\e]122;> \a%}'

This worked fine until I ran into multi-line prompts, specifically Pure-style "pre-prompt" lines.  After some thought and fixes, it now works fine with spaceship-prompt and with the [fish port of pure](https://github.com/rafaelrinaldi/pure).  However, zsh pure doesn't work properly:

![multiline-prompts](https://user-images.githubusercontent.com/10293361/70581111-efb01880-1b6a-11ea-85ad-0413e21f03c2.png)

The default colors are light blue-green for prompts, light yellow for input area, and light beige for input lines as a whole.  The pre-prompt lines `~/DomTerm master*` should be blue-green, and that is correct for fish-pure and spaceship.  However, the original pure, the pre-prompt lines appear in the light yellow of input text.  The reason for that is that pure first displays the pre-prompt correctly (using the escape sequences above), and then it re-paints the pre-prompt without the escape sequences, so they appears to be (echo of) user input.  This causes some problems because the terminal is confused as to what is prompt and what is input.  The visual appearance is also not what it should be.

I don't know zsh much or use it on a regular basis, so I haven't tried to figure out why the pure prints the pre-prompt a second time, this time without the escape sequences.

**Comment by mafredri** [comment]
Hey, thanks for opening this issue, looks like really interesting work you're doing!

The reason you're seeing the current behavior is that Pure dynamically constructs `PS1` depending on what data is available. And we also use a very crude method of determining what is "our" pre-prompt (everything until the last newline), which we then strip out so that we can insert the updated pre-prompt. This should explain the behavior you're seeing.

I actually started (last week) looking into structuring the prompt so that we only need to set PS1 once, but I was on the fence about it since it might be less maintainable. It's the only way I can see us supporting the above use case reliably, though.

**Comment by romkatv** [comment]
@PerBothner Shell integration in iTerm2 works fine with Pure. Perhaps you can implement it the same way? See https://iterm2.com/shell_integration/zsh.

**Comment by PerBothner** [comment]
@romkatv "Shell integration in iTerm2 works fine with Pure."

"Fine" is relative.  I tried the script you linked to (the proposed protocol is an extension of the iTerm2 protocol, so DomTerm also supports the latter). I get the same behavior, with the pre-prompt printed a second time, causing the pre-prompt to be treated and styled as input rather than prompt.

The [iTerm2 screencast](https://iterm2.com/img/screenshots/v3-screen-shots/iterm2-shell-integration-navigation-demo.mov) appears fine because iTerm2 doesn't style prompts distinctly.  Note this isn't just a visual thing: A feature of "shell integration" is so the terminal can know reliably what is input, prompt, or output, which can enable useful and interesting scripts and extensions (such as move cursor on mouse click).

To clarify/repeat: DomTerm with Pure is quite usable - but it would work better and look nicer if we could avoid the second rendering.

**Comment by mafredri** [comment]
@PerBothner are you saying that we should never re-render the prompt, even if the escape sequences are kept? I think that's a non-starter for Pure considering that we do asynchronous work in the background and update the prompt when that information becomes available. We do this for performance / responsiveness reasons and it's one of the major selling points of Pure (for me anyway).

**Comment by romkatv** [comment]
Sorry for sending you on a wild goose chase. I see that indeed Pure doesn't seem to work correctly with iTerm2 shell integration.

I think Pure style in Powerlevevel10k *should* work correctly though. Could you try it? If it's indeed up to your standards, we'll know that this sort of integration is possible.

Type `zsh -f` and then:

```zsh
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
source ~/powerlevel10k/config/p10k-pure.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme
```

**Comment by PerBothner** [comment]
@mafredri "are you saying that we should never re-render the prompt, even if the escape sequences are kept?"

No, I don't mean that. It is always better to avoid duplicate rendering, but it can be difficult to avoid. Especially when a window is re-sized, in which case the simplest solution is to just re-render the whole line.  DomTerm goes through some effort to do the best it can on re-rendering.  It help if you use distinct "start of new command" (emitted by precmd) and "start of prompt" escape sequences (part of PS1).  (ITerm2 combines these, which means it's not as robust wrt re-painting.)

**Comment by PerBothner** [comment]
I got Powerlevevel10k to mostly work, but it works better using [the iTerm2 script](https://iterm2.com/shell_integration/zsh) than the one I wrote for the proposed generic protocol (and specifically DomTerm).  After digging into the things, I realized Powerlevevel10k has hardwired support for iTerm2:

    $ grep SHELL_INTEGRATION_INSTALLED **/*.zsh
    internal/p10k.zsh:  if [[ $ITERM_SHELL_INTEGRATION_INSTALLED == Yes ]]; then  
    internal/p10k.zsh:  _p9k__param_pat+=$'$__p9k_sh_glob\1$ITERM_SHELL_INTEGRATION_INSTALLED\1'
    internal/p10k.zsh:    if [[ $ITERM_SHELL_INTEGRATION_INSTALLED == Yes ]]; then

where `ITERM_SHELL_INTEGRATION_INSTALLED` is set by the above-linked script.

A more portable solution might be to compare PS1 before and after the precmd that add the shell-integration prefix/postfix.  Not sure how best to do that - there may be some execution-order dependencies: in which order precmd functions are executed.

Another approach is to define two variables to hold the prefix and suffix: Maybe`PROMPT_PREFIX` and `PROMPT_SUFFIX`. If these are defined, they can be used by Pure or Powerlevel9k/ Powerlevel10k to wrap PS1 whenever it is (re-)displayed,

I assume the reason spaceship-prompt doesn't have this problem is because it doesn't attempt to dynamically update the prompt.

**Comment by romkatv** [comment]
> Powerlevevel10k has hardwired support for iTerm2

That's correct. The iTerm2 script has several bugs. Helpfully, it has a parameter (`ITERM2_SQUELCH_MARK`) that allows themes to disable the stock shell integration and provide their own. Unfortunately, this parameter disables only one half of the integration but not the rest. Powerlevel10k performs dirty hot patching of iTerm2 integration code to make it work. This patching is fixing only those bugs that affect powerlevel10k more than other themes. There are also bugs in how iTerm2 integration handles interrupts and parse errors. These are fixable but powerlevel10k leaves them be. (I should really send a PR or two to iTerm2.)

I would recommend the following:

1. Clearly document how your terminal uses marks. That is, document the actual protocol rather than a bash/zsh/fish API. I see that you have a document for this purpose (great!) but I haven't read it.
2. Try to make your standard shell integration code work with the most popular themes out of the box. This can be extremely difficult to do for some zsh themes. For example, when using powerlevel10k, you can enable *Instant Prompt* and *Transient Prompt* through `p10k configure`. These are powerful and popular features but they can be very challenging to handle by a generic shell integration script.
3. Honor a parameter that disables shell integration altogether. Advanced themes such as powerlevel10k will have the choice of implementing integration directly against the protocol.

If you need someone to review zsh code, feel free to ping me.

**Comment by mafredri** [comment]
I don't know if this is still relevant, but I also don't think there's anything for us to do here. Pure only redraws the prompt when something has changed and that behavior will not change. For instance, when I `cd` into a git repo, the prompt is redrawn once for git info, an additional time for dirtyness, etc. When git status doesn't change between prompts there are no redraws.

If there's a protocol we can follow to allow terminals like DomTerm to behave ideally, we can re-evaluate.
